# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  XY_USERNAME: ${{ secrets.XY_USERNAME_PRO_TRIAL2 }}
  XY_PASSWORD: ${{ secrets.XY_PASSWORD_PRO_TRIAL2 }}
  XY_URL: ${{ secrets.XY_URL_PRO }}
  XY_PRJ_NAME: LGV-GH-${{ github.event.repository.name }}-CMD

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Git log
        run: git log --all

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      
      - name: Download Xygeni Scanner 
        run: |
          echo Downloading Xygeni Scanner ${{ github.event_name }} ....
          curl -L https://get.xygeni.io/latest/scanner/install.sh | /bin/bash -s -- -u ${{ env.XY_USERNAME }} -p ${{ env.XY_PASSWORD }} -s ${{ env.XY_URL }} -d ${GITHUB_WORKSPACE}/scanner 

      # Runs a set of commands using the runners shell
      - name: Execution Xygeni Scanner (vuln)
        run: |
          echo Executing Xygeni scan ....    
          #${GITHUB_WORKSPACE}/scanner/xygeni scan --never-fail --no-conf-download --skip=codetamper --secrets-mode=history -n ${{ env.XY_PRJ_NAME }}_ALL --dir ${GITHUB_WORKSPACE} -e **/scanner/**
          ${GITHUB_WORKSPACE}/scanner/xygeni secrets --never-fail --no-conf-download --upload -n ${{ env.XY_PRJ_NAME }}_NO_HISTORY --dir ${GITHUB_WORKSPACE} -e **/scanner/**
          #${GITHUB_WORKSPACE}/scanner/xygeni scan --never-fail --no-conf-download --run="secrets" --secrets-mode=history -n ${{ env.XY_PRJ_NAME }}_RUN --dir ${GITHUB_WORKSPACE} -e **/scanner/**
          # --secrets-mode=history
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.
